### ISSUE TITLE
Should I have to install the Gulp Modules Individually?

### ISSUE THREAD

**Issue by clondon** [holger1411/understrap-child#102]
I have tried using Understrap several times.
I do copy the zip files and rename to understrap.  This I extract the file in my WordPress themes directory cd to the directory and do npm install as shown in the instructions on GitHub.
But I get errors at gulp copy-assets about missing dependencies. 

I have to install these individually all of the time.
Is this meant to happen?

..........

**Comment by holger1411** [comment]
Hi!
You log includes your public and private key for your server. Don´t know it it is a public server but you should remove this info from GitHub.

To your problem, run:
`npm install npm@latest -g`
to update npm
Than make sure Gulp is installed globally. Run this:
`npm install --save gulp-install`
to do it.

Than run
`npm install`
again

**Comment by clondon** [comment]
Thank you. I really appreciate your reply, and your work. :-)
