### ISSUE TITLE
Customizer.php missing customizer.js 

### ISSUE THREAD

**Issue by fadingdust** [holger1411/understrap-child#108]
customizer.php requires it to be in ./js. 
gulp copy-assets incorrectly copies customizer.js into ./src/js.

**Comment by holger1411** [comment]
Hi!
Thx for your feedback.
I add an extra task to the parent and child themes gulpfile.js:
https://github.com/holger1411/understrap-child/commit/8c6e00f8a7f0b0a6410b43d920e9e54d1d64a2c9

**Comment by fadingdust** [comment]
Looks like it's the parent understrap theme that needed it, even if the child theme is active. Looks good to me!
