### ISSUE TITLE
Registering Script in Functions.php

### ISSUE THREAD

**Issue by eversionsystems** [holger1411/understrap-child#112]
I've found an issue where if I include some custom scripts in my functions.php file they are not registered unless they are placed in the head.  That is, using wp_register_script() with the last $in_footer parameter set to true will not load my scripts.

**Comment by holger1411** [comment]
Can you post your functions.php?

**Comment by eversionsystems** [comment]
Here the snippet, if I enqueue the last two scripts ( owl-carousel and home-page) in the footer it doesn't render my carousel.  Changing it to the header it works.

```
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

function theme_enqueue_styles() {

	// Get the theme data
	$the_theme = wp_get_theme();

    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array(), $the_theme->get( 'Version' ) );
    wp_enqueue_script( 'jquery' );
	wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), false);
    wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.js', array(), '1.0', false );
	
	wp_register_script( 'retina', get_stylesheet_directory_uri() . '/js/retina.min.js', array(), '1.3', false );
	wp_enqueue_script( 'retina' );
	
	wp_register_style( 'owl-carousel', get_stylesheet_directory_uri() . '/css/owl.carousel.min.css' );
	wp_enqueue_style( 'owl-carousel' );
	wp_register_style( 'owl-theme', get_stylesheet_directory_uri() . '/css/owl.theme.default.min.css' );
	wp_enqueue_style( 'owl-theme' );
	
	wp_register_script( 'owl-carousel', get_stylesheet_directory_uri() . '/js/owl.carousel.min.js', array(), '2.2.0', true );
	wp_enqueue_script( 'owl-carousel' );
	
	wp_register_script( 'home-page', get_stylesheet_directory_uri() . '/js/home-page.js', array( 'jquery', 'owl-carousel' ), '1.0.0', true );
	wp_enqueue_script( 'home-page' );
}
```

**Comment by axlright** [comment]
@eversionsystems in case it's helpful, a workaround for this that may also have page speed / SEO benefits is to compile your owl-carousel and home-page js scripts into the main child-theme.min.js script which sits in the footer. That way the viewer is only loading one single script. That's what I do and it works well.

**Comment by Thomas-A-Reinert** [comment]
Just go with something like 
`wp_enqueue_script( 'backstretch', get_stylesheet_directory_uri() . '/js/jquery.backstretch.min.js#asyncload', array(), $the_theme->get( 'Version' ), true );`
Never had any problems in an UnderStrap Child theme using that. Never used a wp_register_script.

**Comment by eversionsystems** [comment]
Thanks guys I'll try compiling into the footer.
