### ISSUE TITLE
About overwriting global template.

### ISSUE THREAD

**Issue by tonbo** [holger1411/understrap-child#118]
When I add the child theme, can I overwrite the global template for example hero.php?
I want to add some css features and html code on hero.php, but it is in global template directory.
What is the better way to add the change on .php in global template directory as the understrap's common role?

**Comment by axlright** [comment]
You can copy files from the parent theme into the child theme and modify them there. WordPress will look for the files in the child theme first, and this way you've not modified anything in the parent theme. Just be sure to duplicate the directory structure of files you copy from the parent theme to the child theme.

**Comment by tonbo** [comment]
I understand. You meant global template would include this theory.
 Now I am just familiar with understrap template theory, and I assume, I should not overwrite global template directory but if I need, I can do.
Thank you.
