### ISSUE TITLE
Owl carousel

### ISSUE THREAD

**Issue by DigiPez** [holger1411/understrap-child#15]
Put simply, how do I get the owl carousel to appear on my custom home page template? I only want it to exist on the home page. I am developing through Wordpress.org.

At the moment I am sourcing the slider script in the template file but nothing appears to be happening... I am a beginner when it comes to using frameworks so it's probably something real simple!

**Comment by brandon-morgan** [comment]
@DigiPez 

This is what I did...

**Add following to the top of your custom home page template**
`<div class="wrapper" id="wrapper-hero">
    <?php if ( is_active_sidebar( 'hero' ) ) : ?>
	<div class="owl-carousel">
		<?php dynamic_sidebar( 'hero' ); ?>
	</div>
<?php endif; ?>
</div>`
This grabs the Hero Slider widget. You will need to then navigate to your widgets and find the _**Hero Slider**_ widget. As it says, you need add at least two widgets. If you want to have a test that looks exactly like the demo then add the following html inside a text widget w/o title.

**First Text Widget**
`<div class="jumbotron">
                    <div class="container">
      <div class="row">
                            <div class="col-md-8">
                                  <h1>First Slide</h1>
                                  <p>Welcome to the UnderStrap Demo site. UnderStrap is a WordPress theme framework based on Bootstrap SASS, the Underscores starter theme and some more usefull functions and scripts.</p>
                                  <p><a class="btn btn-primary btn-lg" href="https://github.com/holger1411/understrap" role="button" target="_blank">See it on GitHub <i class="fa fa-github" aria-hidden="true"></i>
</a></p>
                            </div>
                        </div>
</div>
                </div>`

**Second Text Widget**
`<div class="jumbotron">
                    <div class="container">
      <div class="row">
                            <div class="col-md-8">
                                  <h1>Second Slide</h1>
                                  <p>Welcome to the UnderStrap Demo site. UnderStrap is a WordPress theme framework based on Bootstrap SASS, the Underscores starter theme and some more usefull functions and scripts.</p>
                                  <p><a class="btn btn-primary btn-lg" href="https://github.com/holger1411/understrap" role="button" target="_blank">See it on GitHub</a></p>
                            </div>
                        </div>
</div>
                </div>`

That should do it! Let me know if you don't get it going.

**Comment by blowsie** [comment]
+1

**Comment by holger1411** [comment]
Owl slider was removed and replaced with the default Bootstrap build-in slider.
So this Issue is obsolet...;-)

**Comment by blowsie** [comment]
Is there an example of the BS carousel working?

**Comment by holger1411** [comment]
Yes, the demo homppage use it:
https://understrap.com/understrap/

It is used as a build-in widget slider

**Comment by xicubed** [comment]
Does the core child theme need to get rid of references to owl-carousel? Get my gulp watch-bs gives an error when it recompiles... There's still a blablabal/wp-content/themes/core-understrap-1-0-7/sass/assets/owl-carousel2.scss

`Message:
    sass/assets/owl-carousel2.scss
Error: File to import not found or unreadable: ../../src/sass/owl-carousel2/owl.carousel.
        on line 1 of sass/assets/owl-carousel2.scss
        from line 10 of sass/child-theme.scss
>> @import "../../src/sass/owl-carousel2/owl.carousel";
`
