### ISSUE TITLE
Child theme localisation

### ISSUE THREAD

**Issue by alesandar** [holger1411/understrap-child#16]
My **/languages** directory is not respected. Placing the appropriate **.po** file and the corresponding **.mo** one within my child theme directory doesn't localise anything. However, if I put them in my parent theme directory, everything's just fine.

I've also tried to copy _**understrap**/inc/setup.php_ to _**understrap-child**/inc/setup.php_ and add `load_child_theme_textdomain( 'understrap-child', get_template_directory() . '/languages' );` immediately after `load_theme_textdomain( 'understrap', get_template_directory() . '/languages' );`, but without any success.

What's the right place for my localisation files? Are they going to be removed, after a theme update?

**Comment by holger1411** [comment]
Hi! Pls try this:
http://wpexplorer-themes.com/total/docs/child-theme-translation-files/
Add it right at the beginning of your child themes function.php

**Comment by alesandar** [comment]
Works like a charm, thanks a lot!
