### ISSUE TITLE
Don't match the template name of the parent theme and the parent theme folder name

### ISSUE THREAD

**Issue by fcojgodoy** [holger1411/understrap-child#2]
In 'style.css' the template name of the parent theme don't match with the parent theme folder name. The first is 'understrap' and the second is 'understrap-master'.

**Comment by holger1411** [comment]
Hi!

If you download the master branch here from Github, Github names the file "understrap-master". Thats nothing I can control (as far as I know...).

**Comment by dvlopes** [comment]
@holger1411 consider updating README.md file to include instructions to rename the folder as in https://github.com/dvlopes/understrap-widgets#instalation

By the way, I created this [plugin](https://github.com/dvlopes/understrap-widgets) that adds widgets designed for Understrap (Bootstrap Markup actually) and kinda stealed the name, hope you don't mind =oP

**Comment by xavierve** [comment]
that's true , hi. in order to work, i needed to change root style.css Template: understrap-master to point right to master theme
please include advise in readme, thanks
