### ISSUE TITLE
Disable Parent theme functions

### ISSUE THREAD

**Issue by rikrog** [holger1411/understrap-child#23]
Hello

I am very new to Git (and quite new to frameworks).. So please bear with me!

I'm looking to disable parent theme functions and struggling to find a way which works!

The particular function I'm looking to disable is 'all_excerpts_get_more_link' in the parent theme setup.php

Googleing about I find mentions making of parent theme functions 'pluggable'. This could be an option for you with understrap?

Thanks!

**Comment by holger1411** [comment]
Hi!
Sorry for the late reply...seems I miss this issue.

Since UnderStrap 0.5.0 all major functions are plugable.
Means if you define the function in yur child theme the parent theme will not load its own function any more.

**Comment by rikrog** [comment]
Hello! Also sorry for even reply to your reply. 

Will go and have a play with these pluggables!
