### ISSUE TITLE
Line 23 of _variables.scss: Invalid CSS after " @each $key": expected "in", was ", $num in $map {")

### ISSUE THREAD

**Issue by onepartscissors** [holger1411/understrap-child#26]
Hi there

I am not using bower, i am just intending to use plain old Scout 0.7.1 to render the sass into css, but when i try and compile, i get the following error on the file "src/sass/bootstrap4/_variables.scss":

`Line 23 of _variables.scss: Invalid CSS after " @each $key": expected "in", was ", $num in $map {")`

Line 23 looks like this, and to my eye, looks like correct sass:

`@each $key, $num in $map {`

Do you have any idea why this won't compile? What might i be missing?

**Comment by holger1411** [comment]
It comes directly from the Bootstrap 4 project and seems to be correct SASS. Compiles via Gulp/Sass perfectly. 
Maybe it isnt supported by your Scout version?
I mean Scout 0.7.1 is nearly five years old...v2.6.8 is the latest version.

**Comment by onepartscissors** [comment]
OK, must be the compiler then, thank you @holger1411.

worried about the new scout because it doesn't support full compass, it says it supports 'Only Mixins', not full support, but i will try it!

Thank you for the speedy reply!
