### ISSUE TITLE
mobile nav isn't working

### ISSUE THREAD

**Issue by mmatthews1981** [holger1411/understrap-child#27]
check it out, live on repcapitalmedia.com. I can't get any mobile nav love.

**Comment by holger1411** [comment]
Hi!
Seems you use an older Parent and/or Child theme combination.

Your website says: 
`Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)`

Later versions of Bootstrap 4 Alpha use this script to reveal or hide something (including the mobile nav).

Please make sure you update your parent theme to 0.5.0.

Than make sure you use the latest package.json file from child theme, available here:
https://github.com/holger1411/understrap-child/blob/master/package.json

Download it into your child theme directory (and overwrite the old one) and than run:
`npm install`

followed by:
`gulp copy-assets`

and than recompile your child themes JS file with
`gulp scripts`

**Comment by jimkrill** [comment]
It looks like Tether is INSIDE the ./node_modules/bootstrap/node_modules/ folder and gulpfile.js is looking for it in ./node_modules/ in the copy-assets task... 

To fix this, you can run `npm install tether --save` and then `gulp copy-assets` and `gulp scripts` as suggested above... should fix it.

Tether is not in the dependencies listed in package.json that you pointed to above... it IS a dependency of Bootstrap, but then you should reference it at ./node_modules/bootstrap/node_modules/tether/

**Comment by holger1411** [comment]
if you run "npm install" it will install all dependencies, including the Bootstrap 4 dependencies like Tether.
So normally there should be an /node_modules/theter folder which than could be moved by "gulp copy-assets" to the source folder

**Comment by jimkrill** [comment]
Hmm... you are right. I just did a fresh clone and `npm install` and tether is there in node_modules... I wonder what happened the first time.

Thanks!
