### ISSUE TITLE
Can't use understrap-child with prepros anymore.

### ISSUE THREAD

**Issue by josephlariosa** [holger1411/understrap-child#28]
Hi Holger, I can't use the understrap-child theme anymore with prepros scss preprocessor 
it prompts me this error.

file to import not found or unreadable: ../../src/sass/bootstrap4/media/galleries
Current dir: D:/xampp/htdocs/personal/hugot/wp-content/themes/understrap-child/sass/assets/ on line 42:9 of D:/xampp/htdocs/personal/hugot/wp-content/themes/understrap-child/sass/assets/bootstrap4.scss
D:\xampp\htdocs\personal\hugot\wp-content\themes\understrap-child\sass\child-theme.scss

**Comment by josephlariosa** [comment]
Solved!

Issue : src folder is not included in understrap-child
and I renamed the directory underscore to underscores.

**Comment by holger1411** [comment]
Please run
`npm update`
and than
`gulp copy-assets`
in your child theme root directory

The first task downloads all assets and updates them, the second creates the /src folder and adds all needed fils to it.

**Comment by holger1411** [comment]
Is made easier with:
https://github.com/holger1411/understrap/pull/188

`npm install` now runs `gulp copy-assets` automatically after it is done
