### ISSUE TITLE
Too many pagination

### ISSUE THREAD

**Issue by ryanrahman26** [holger1411/understrap-child#29]
![1](https://cloud.githubusercontent.com/assets/20228877/21296487/8130acf4-c59f-11e6-9c59-3a399dfbaa8e.jpg)

How to disable the WordPress default ? so i can use the default UnderStrap pagination.

**Comment by holger1411** [comment]
Hi!
Hm, seems you use some different parent/child theme combination.
Make sure to use UnderStrap 0.5.0 and Child v 0.1.6
And, if you already do some changes recompile anything.

The black "older posts" button don´t looks like the WP nor UnderStrap default....
If nothing helps feel free to send me your URL

**Comment by ryanrahman26** [comment]
![1](https://cloud.githubusercontent.com/assets/20228877/21341944/c1522510-c6c1-11e6-9f01-f6365a402848.jpg)

Hello..
I do not use a child theme, I just use UnderStrap parent theme, and this is still in localhost. The problem is still not finished, infinite scroll behaviour default wordpress 4.7 if enabled will bring up the black button older post as first image, if it is turned off infinite scroll it will load the whole page is not limited only to 4 (image on this thread). I just wanted to show 4 posts on the homepage without any black order post default wordpress (just using UnderStrap default), how do I resolve this?

**Comment by holger1411** [comment]
Hi!
That "Infinite Scroll Behavior" is not a WP default function.

Seems there is another Plugin involved (maybe Jetpack?). Please check your plugins page and disable the Plugin to verify if thats the reason or not.

**Comment by holger1411** [comment]
Okay, seems a Jetpack issue. If you don´t want to use the Infinite Scroll behavior make sure you disable the feature on your Jetpack Settings page, too.
On "Jetpack -> Settings -> Appereance"

![screenshot-understrap com 2016-12-20 08-56-19 jpeg](https://cloud.githubusercontent.com/assets/1568158/21342437/332dd646-c692-11e6-8f49-29da79477ab1.jpg)

**Comment by ryanrahman26** [comment]
:)
Yes have completed the first issue apparently comes from the jetpack, sorry I did not check it twice. The next is there are 'Post navigation' and link 'older posts'. in the demo (https://understrap.com/understrap/ ) I saw nothing. How to remove it?
![2](https://cloud.githubusercontent.com/assets/20228877/21342514/e058b994-c6c4-11e6-922b-a24ea6f43988.jpg)

**Comment by holger1411** [comment]
Hi! No problem.
But the "older posts" link did not appear on the demo page. It was replaced by the pagination nav.

While the demo page uses the latest pre-release 0.5.1 version (and there are several changes and bug fixes related to this) it might be an already fixed bug.
Please download this version here:
https://github.com/holger1411/understrap/releases/tag/0.5.1
extract it and overwrite your files in your /themes/understrap folder with it.

Clear all caches and recheck.

Let me know what happend!

**Comment by ryanrahman26** [comment]
Nothing changed. 'Post navigation' and links 'older posts' were still there. Even I had a fresh install using understrap 0.5.1.zip and upload it to wordpress. Any suggestion ?

**Comment by holger1411** [comment]
Hi!
Sorry, there is no code for the old default WP nav in the template files.
Please see here:
https://github.com/holger1411/understrap/blob/master/index.php#L64
It just loads the understrap pagination.

Can you post the content of your understrap/index.php file?
Or a screenshot of the full source code?

**Comment by holger1411** [comment]
Oh, and make sure you clean up anykind of caching. Browser caching or any WP or Server Caching

**Comment by ryanrahman26** [comment]
This is my [index.php](http://pastebin.com/7Vgs0RfC). I have not made any changes in the theme. Only fresh install and pagination of its own like that. Firefox cache was deleted and the same.

**Comment by holger1411** [comment]
Can you post the source code of your rendered page?

**Comment by ryanrahman26** [comment]
If not, it's okay, now I just want to try understrap :) [index.html](http://pastebin.com/jGbb9gtj)

**Comment by holger1411** [comment]
Its a very stange thing. The code itself is nowhere in your source code.
And it works on our demo site: https://understrap.com/understrap/

Hmmm
But your site still loads:
http://localhost/buffet/wp-content/themes/understrap-0.5.1/js/theme.min.js?ver=0.5.0

`?ver=0.5.0` indicates that the version number in your style.css is still 0.5.0...which means something isnt updated or something is cached because the latest version of this file looks like:
https://github.com/holger1411/understrap/blob/master/style.css#L10

`Version: 0.5.1`

Do you have another /understrap folder in your /themes directory?
If so please delete it.

**Comment by ryanrahman26** [comment]
understrap-0.5.1.zip file seems wrong, in style.css still version 0.5.0

**Comment by holger1411** [comment]
%&?! Sorry...I just did not update the pre-release.
Now everything should be in

**Comment by ryanrahman26** [comment]
Ok, It is finished. thanks.
