### ISSUE TITLE
Display owl carousel on all pages

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap-child#31]
I'm calling the owl carousel in my header.php and it works fine on my homepage. It's being called on the interior pages but it looks like it's not adding the "owl-loaded" class. I can think of a hack to make it work but I wanted to see if there was a proper way to make this display on all pages. 

example code: `<div class="header-image"><?php get_sidebar('hero'); ?></div>`

Link: http://cityofchildress.com/event-center/

**Comment by holger1411** [comment]
Pls check inc/enqueue.php ´s line 38 from the parent theme:
https://github.com/holger1411/understrap/blob/master/inc/enqueue.php#L38
It loads the corresponding script only if the page is "home"
Remove this
`if ( is_front_page() ) {`

and the ending
`}`

if you want to load the slider settings script on all pages

**Comment by tellstevens** [comment]
That worked. Thanks
