### ISSUE TITLE
Updating the child theme

### ISSUE THREAD

**Issue by alwaysalready** [holger1411/understrap-child#32]
Just wondering what the best way to update the child theme is. What files and directories can I safely update? Sorry if this is in a read me - I don't think I see any information about updates.

**Comment by holger1411** [comment]
Hi!
The problem is it depends on what files you are changed in your child theme, so there is no global rule for it.

If you just add new files you are good to go. If you change exisiting core files of the child theme they will be overwritten if you just copy and paste all files.

**Comment by alwaysalready** [comment]
Thanks so much for the quick reply Holger. That makes sense.
