### ISSUE TITLE
Registering Sidebars

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap-child#35]
I tried just copying the inc/widgets.php into my child theme and registering a new sidebar that way but it doesn't seem to work. I just went in and added it to the parent theme but obviously that gets screwed up when we update. What is the proper way to do that?

**Comment by holger1411** [comment]
Hi!
Create a functions.php in your child theme folder and call your inc/widget.php file from there or add your code directly to the functions.php in your child theme.

**Comment by tellstevens** [comment]
oh geez. How did I not think about need to call the widget.php from there? Thanks
