### ISSUE TITLE
Hamburger items allways open

### ISSUE THREAD

**Issue by float1** [holger1411/understrap-child#38]
hi, i don't know where to ask this as i am new to this things but when i resize browser hamburger is opened and cant close it.

![outputham](https://cloud.githubusercontent.com/assets/7194552/22622980/3e2887ca-eb4b-11e6-89ba-ad96c68bef77.gif)

**Comment by float1** [comment]
oh i think it was my fault i copied fresh files over my modified and it works, sorry to bother

**Comment by holger1411** [comment]
No problem!
