### ISSUE TITLE
Do you really need the child theme?

### ISSUE THREAD

**Issue by barnettj7** [holger1411/understrap-child#4]
Hi,

I am having issues getting the child theme functions, ect. to register new widgets ect. I was wondering if it is necessary to use the child theme, or can you use understrap as a starter framework, without any issues upgrading the core?

Much Appreciated. 

Jeff

**Comment by holger1411** [comment]
Of course you can use the parent theme and change it the way you want. But if there are updates you have to incorporate them manually. If you just overwrite it you will overwrite your changes.
So if you plan to use the UnderStrap core/parent in the future, the child theme is the way to go.

May I ask what kind of problems do you have registering a widget?

**Comment by barnettj7** [comment]
I am trying to register a new widget in the inc/widgets.php. I have created the folder and file in the child theme, and have tried the following two ways to register it. 

function understrap_widgets_init() {
	register_sidebar( array(
		'name'          => __( 'Left Sidebar', 'understrap' ),
		'id'            => 'sidebar-2',
		'description'   => 'Left Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );
add_action( 'widgets_init', 'understrap_widgets_init' );

and also ...

function understrap_master_child_widgets_init() {
	register_sidebar( array(
		'name'          => __( 'Left Sidebar', 'understrap' ),
		'id'            => 'sidebar-2',
		'description'   => 'Left Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );
add_action( 'widgets_init', 'understrap_master_child_widgets_init' );

Here is my child theme functions.php

<?php
function understrap_remove_scripts() {
    wp_dequeue_style( 'understrap-styles' );
    wp_deregister_style( 'understrap-styles' );

    wp_dequeue_script( 'understrap-scripts' );
    wp_deregister_script( 'understrap-scripts' );

    // Removes the parent themes stylesheet and scripts from inc/enqueue.php
}
add_action( 'wp_enqueue_scripts', 'understrap_remove_scripts', 20 );

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array());
    wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.min.js', array(), '0.1.0', true );
     wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/custom.js', array(), true );
}
// Create a custom image size for Site Logo.
add_image_size( 'mytheme-logo', 300, 111 );
 
// Declare theme support for Site Logo.
add_theme_support( 'site-logo', array(
    'size' => 'mytheme-logo',
) );

I cannot get the file to register when using the child theme, but if I add the first code in the parent theme, it will register. Do you see any issue with my process, or can you provide me with direction to get the functions to register.

Thank you!

Jeff

**Comment by holger1411** [comment]
If you create a new /inc folder with a new widgets.php file inside your child theme´s directory you have to load this external file in your child themes function.php, too.

Add this:
require get_stylesheet_directory() . '/inc/widget.php';

This loads the widget.php file from the child theme, too.

**Comment by barnettj7** [comment]
Thank you I got it working now! 

Do I have to repeat the same process for /loop-templates , /page-templates , /widget-templates , /fonts , ect. and so on?

I would like to create this website to be completely child theme oriented to ensure that updates do not overwrite the files.

Thank you for your help so far.

-Jeff

**Comment by barnettj7** [comment]
Actually I just noticed that the widgets file is still not loading. I have tried several ways, but still won’t work.

Here is the functions.php 

<?php get_stylesheet_directory() . '/inc/widgets.php'; ?>
<?php
function understrap_remove_scripts() {
    wp_dequeue_style( 'understrap-styles' );
    wp_deregister_style( 'understrap-styles' );

    wp_dequeue_script( 'understrap-scripts' );
    wp_deregister_script( 'understrap-scripts' );

    // Removes the parent themes stylesheet and scripts from inc/enqueue.php
}
add_action( 'wp_enqueue_scripts', 'understrap_remove_scripts', 20 );

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array());
    wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.min.js', array(), '0.1.0', true );
     wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/custom.js', array(), true );
}
// Create a custom image size for Site Logo.
add_image_size( 'mytheme-logo', 300, 111 );
 
// Declare theme support for Site Logo.
add_theme_support( 'site-logo', array(
    'size' => 'mytheme-logo',
) );


Please help!

Thank you

**Comment by barnettj7** [comment]
Here is my widgets.php file. do I need to add the understrap_child_master_widgets_init or just understrap_widgets_init to the following sections. Nothing is registering still. 

<?php
/**
 * Declaring widgets
 *
 *
 * @package understrap
 */
function understrap_child_master_widgets_init() {
	
	register_sidebar( array(
		'name'          => __( 'Left Sidebar', 'understrap' ),
		'id'            => 'sidebar-2',
		'description'   => 'Left Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

}
	register_sidebar( array(
		'name'          => __( 'Right Sidebar', 'understrap' ),
		'id'            => 'sidebar-3',
		'description'   => 'Right Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

}
	register_sidebar( array(
		'name'          => __( 'Both Left Sidebar', 'understrap' ),
		'id'            => 'sidebar-4',
		'description'   => 'Both Left Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

}
	register_sidebar( array(
		'name'          => __( 'Both Right Sidebar', 'understrap' ),
		'id'            => 'sidebar-5',
		'description'   => 'Both Right Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

}
add_action( 'widgets_init', 'understrap_child_master_widgets_init' );

Thanks.

Jeff

**Comment by barnettj7** [comment]
So basically I have found a slight work around, but will still like to use the inc/widgets file

my functions.php works correct with this code to remove_action

<?php
/**
 * Register widget area.
 *
 * @link http://codex.wordpress.org/Function_Reference/register_sidebar
 */
function understrap_remove_scripts() {
    wp_dequeue_style( 'understrap-styles' );
    wp_deregister_style( 'understrap-styles' );

    wp_dequeue_script( 'understrap-scripts' );
    wp_deregister_script( 'understrap-scripts' );

    // Removes the parent themes stylesheet and scripts from inc/enqueue.php
}
add_action( 'wp_enqueue_scripts', 'understrap_remove_scripts', 20 );

add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'child-understrap-styles', get_stylesheet_directory_uri() . '/css/child-theme.min.css', array());
    wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/child-theme.min.js', array(), '0.1.0', true );
     wp_enqueue_script( 'child-understrap-scripts', get_stylesheet_directory_uri() . '/js/custom.js', array(), true );
}
// Create a custom image size for Site Logo.
add_image_size( 'mytheme-logo', 300, 111 );
 
// Declare theme support for Site Logo.
add_theme_support( 'site-logo', array(
    'size' => 'mytheme-logo',
) );
remove_action('widgets_init', 'understrap_widgets_init');
add_action('widgets_init', 'understrap_widgets_init');
function understrap_widgets_init () {
	register_sidebar( array(
		'name'          => __( 'Left Sidebar', 'understrap-child-master' ),
		'id'            => 'sidebar-2',
		'description'   => 'Left Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	register_sidebar( array(
		'name'          => __( 'Right Sidebar', 'understrap-child-master' ),
		'id'            => 'sidebar-3',
		'description'   => 'Right Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	register_sidebar( array(
		'name'          => __( 'Both Left Sidebar', 'understrap-child-master' ),
		'id'            => 'sidebar-4',
		'description'   => 'Both Left Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );

	register_sidebar( array(
		'name'          => __( 'Both Right Sidebar', 'understrap-child-master' ),
		'id'            => 'sidebar-5',
		'description'   => 'Both Right Sidebar widget area',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h3 class="widget-title">',
		'after_title'   => '</h3>',
	) );	
}

I am wondering if I can use the remove_action or something similar to unregister the inc/widgets.php code. 

The code you initially sent still throws an error because it is trying to call both files. So I think I must unregister the parent them widgets.php and include or require the child themes widgets.php file. 

Can you please provide the code or point me in the right direction to accomplish this?

Thanks,

Jeff

**Comment by holger1411** [comment]
Hi!
Basically:
> "Do I have to repeat the same process for /loop-templates , /page-templates , /widget-templates , /fonts , ect. and so on? I would like to create this website to be completely child theme oriented to ensure that updates do not overwrite the files."

If you want to replace 50%+ of the parents themes php files by your child themes php files it might be easier to work on your own version of UnderStrap and use it as parent theme.
Use as starter theme. Take it, change it and use it your way.

To the problem itself:
**Could you post the exact error message?**
Normally it should be no problem to load an php file but deregister its action/function.

Sounds more like a loading priority.
The child theme functions.php is loaded on top of the parent themes functions.php.

Means in your case:
1.Deregister an action which isn´t registered jet
2.Load the child themes widget.php and register a action called "understrap_widgets_init"
3.Load the parent themes widget.php and register agaon another action with the same name

The solution could be changing the loading sequence by adding a priority to the add_action and remove_action

See Codex here (for remove_action):
https://codex.wordpress.org/Function_Reference/remove_action
and (for add_action):
https://developer.wordpress.org/reference/functions/add_action/

The default priority (if nothing is set) is "10"
Set it to "20" for removing the parent´s action and to "30" for adding your child themes action.
It will change the sequence to:
1. Load the parent themes widget.php and register the action
2. Deregister the parent theme action
3. Register the child themes action

Sample Code for your child themes functions.php:
```
remove_action('widgets_init', 'understrap_widgets_init',20); 
add_action('widgets_init', 'understrap_widgets_init',30);
```
Let me know if this helps!

**Comment by nd-github** [comment]
Hi Holger,

Understrap and understrap-child is a great project.

I have set up Understrap and the understrap-child theme.
Is experimenting around with the features and can´t get the Hero slider Widget to work when using the child theme. Shifting back to Understrap theme the slider works perfect.
Any Idea off what I might do wrong or how to solve the situation?

With best regards
Niels

**Comment by holger1411** [comment]
If you activate the Child Theme you have to create and place the Widgets for it too.
WP stores the widgets theme related, if you switch the theme (even if it is a child theme) you have to set them up for the other theme too.

**Comment by nd-github** [comment]
Hi Holger,

Thanks for the quick response.
I did try what you suggest before writing you and just tried it again. Still the Hero slider widget does not appear in the child theme. Also I just tried to make the Hero Static work in the child theme - and this is working fine. I am on the latest versions of everything... Can you think for any other reason(s)? Is it working in your set up?

With best regards
Niels

**Comment by holger1411** [comment]
Yes, works here. Could you post the URL?

**Comment by holger1411** [comment]
Sorry, found it out. Check https://github.com/holger1411/understrap-child/commit/44fee3311ef2aecfa56405a8aa472e0168e7c79e
The slider_settings.js file was missing in child themes JS folder. 
It works here locally but it seems I forgot to add it to my git...

**Comment by nd-github** [comment]
Hi Holger,

Thanks, works great now.

With best regards
Niels

**Comment by nailbrain** [comment]
I'm having the same issue. Can't load a new sidebar in a child theme.

**Comment by holger1411** [comment]
How and where do you integrate into which (template-) file?
