### ISSUE TITLE
navabar height

### ISSUE THREAD

**Issue by uitta** [holger1411/understrap-child#42]
Hi.
I cannot understand how to use the $navbar-height variable in the _child_theme_variables.scss

Every value i choose it simply doesn't change anything. Looking at the files i understood it's only used in a mixins named navbar-vertical-align() in _navbar-align.scss, but if i try to include it in my _child_theme.scss and then gulp watch, it say "no mixin named navbar-vertical-align".
Am i missing something?

**Comment by holger1411** [comment]
Hi!
Yes, thats just an relic from Bootstrap 4 alpha 5. Alpha 6 used a differend navbar construction without fixed height values.

All variables regarding the navbar from BS4 can be found here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L576
If you wanna change a variable copy it to your child themes variables file, change the value, remove the `!default` and recompile your scss to css

**Comment by holger1411** [comment]
I will remove the useless varibale from the child theme, too

**Comment by uitta** [comment]
Ok.
Thanks for the amazing job.

**Comment by holger1411** [comment]
Was removed here:
https://github.com/holger1411/understrap-child/commit/a6801fe034dd6094329745c8c6d30a208976a8b1

I will close this. But feel free to reopen it if you have more questions
