### ISSUE TITLE
Unavailable sass references

### ISSUE THREAD

**Issue by ErinPo** [holger1411/understrap-child#48]
The child theme description says it is configured to compile its CSS based on the SCSS from the parent theme. However, looking into child-theme.scss and its import statements, much of the SCSS is really being pulled from a folder 'understrap-child/src'. A folder named 'src' doesn't actually exist in the child theme. It exists only in the source download of the parent theme. 

Shouldn't these references be pointing to '../../understrap/src/sass/*' instead, so that they compile against the parent theme?

**Comment by holger1411** [comment]
No, if you run the command:
`npm install`
it downloads the parent themes sources and moves them to the source folder.
Than anything is in place and you can compile the child themes CSS with all needed portions of the parent theme.

**Comment by ErinPo** [comment]
Oh, I see, sorry. I didn't want to use npm, instead compiling on the server and updating understrap via WP. I just copied the sources myself. Hm, too bad the src folder is not part of the WP package.

**Comment by ErinPo** [comment]
Do you know if the WP theme update routine for understrap will delete the src folder if I manually move it under there (and symlink it to my various child themes)?

**Comment by ErinPo** [comment]
This was actually easy to test by lowering the theme version in style.css. The answer is the folder is overwritten:(

**Comment by ErinPo** [comment]
I found a plugin that installs understrap from Github instead and this way the source folder is included - nice:) Looking forward to playing around with your theme.

**Comment by holger1411** [comment]
I re-add the /src folder by default to the wp.org donwload version to avoid confusions.
So you don´t need to run npm install before you can compile the sass sources to css.

thx @ErinPo for metion this problem!
