### ISSUE TITLE
Not compiling in child-theme

### ISSUE THREAD

**Issue by christian70** [holger1411/understrap-child#55]
After updating to new release, the css file is not compiled in child-theme. If I make changes in child theme variables, the files have been watched - as I can see in node console - but it has no effect on the final style. Before it used to work, very very slow, but now only parent theme seems to work properly as far as sass is concerned.

**Comment by christian70** [comment]
Anybody'got problems with the new version? I confirm, in my case, the previous release of child theme works fine (even if cssnano makes the process very slow, about 6s) but it works, at the contrary the latest version doesn't work at all. Any help? Suggestions?

**Comment by holger1411** [comment]
Was fixed a few minutes ago here:
https://github.com/holger1411/understrap-child/commit/f5292b61d14fd23f114537d3268518c57c5ff456#diff-b9e12334e9eafd8341a6107dd98510c9

It was a simple "copy&paste" problem.
I just copied the new "minify-css" task from the parent themes gulpfile to the child theme...without changing the css file name from "theme.css" to "child-theme.css"...

So it just tries to compile a not present file...

**Comment by christian70** [comment]
Thank a lot, I'll make another attempt right away... looking forward to work on Understrap.

**Comment by christian70** [comment]
Now everything works just fine, and it is as fast as the parent theme. I've already stood you a beer, but I think you deserve another one soon. Cheers.

**Comment by bidays** [comment]
Thank you soo much... I was going nuts...
Please Update this issue on the website.

**Comment by holger1411** [comment]
I released a quick fix version 0.3.1: https://github.com/holger1411/understrap-child/releases/tag/0.3.1
