### ISSUE TITLE
Problems using gulp watch to update CSS

### ISSUE THREAD

**Issue by dantzlerwolfe** [holger1411/understrap-child#58]
When I add `#wrapper-static-hero { padding: 0; }` to `_child_theme.scss`, `gulp watch` detects the change and seems to be functioning normally. However, I don't see the style updated in the css files, nor does it show up in the browser. Am I missing something?

Also (not sure if this is related), `child-theme.min.css` disappears if I try to directly modify `child-theme.css` while `gulp watch` is running. I was looking to modify `child-theme.css` directly as a workaround for the problem above.

**Comment by jrglass** [comment]
I'm having the same issue when adding styles to `_child_theme.scss` with `gulp watch` running. It all shows up correctly in the `child-theme.css` file but for some reason it's not compiling it into the minified version: `child-theme.min.css`. Thus, the styles aren't enqueueing when the page is built.

Any ideas why it's not compiling from `child-theme.css` > `child-theme.min.css`?

**Comment by jrglass** [comment]
@dantzlerwolfe, after some experimenting, I figured out the issue with why it's not updating the css and min.css files.

In the sass > theme folder, the files are named `_child_theme.scss` and `_child_theme_variables.scss`. Rename those files so the beginning `_` is removed. So now they are named `child_theme.scss` and `child_theme_variables.scss`.

Not exactly sure why that was never mentioned in the readme for the child theme but I noticed that the sass > child-theme.scss file imports the file names without the `_`.

Not sure if this is actually correct, but it's now working fine for me when I update anything.

@holger1411, can you confirm?

Hope that helps.

**Comment by dantzlerwolfe** [comment]
@jrglass I had a copy of understrap-child that was several weeks old. On May 2, @holger1411 made a commit that solved the minifying css problem in the gulpfile. After updating my gulpfile appropriately, my scss updates seem to work fine (I actually reinstalled understrap-child completely, but I think you could get away with just updating `package.json` and `gulpfile.js` and running `npm install`). Not sure if/how this might relate to your issue unless you are similarly using an older copy.

As I add more styling, I'll post updates here. Hopefully everything will work.

**Comment by qvarting** [comment]
I have the same problem as you guys.
Editing the parent theme is now problem, but editing the child-theme works "now and then".
Have you tried after the migration to bootstrap beta?

**Comment by qvarting** [comment]
I installed sass and using this instead,
`sass -t compressed child-theme.scss > ../css/child-theme.min.css`

Cheers
