### ISSUE TITLE
browserSync reload

### ISSUE THREAD

**Issue by akkolad** [holger1411/understrap-child#6]
Hi,

I've just download understrap, and I just added a fonctionality to browserSync which save a lot of time : the "live reload".
I can't code without this feature, I've added it to my project in the gulpfile like this : 
`var reload = browserSync.reload;`
bellow 
`var browserSync = require('browser-sync').create();`

And in the cssnano task, I've added this pipe :
`.pipe(reload({stream: true}));`

And it works fine for me.

Will you plan to insert this feature in your master ?

Understrap seems to be a good job anyway !

**Comment by holger1411** [comment]
Hi!
Sounds cool. Feel free to open a pull request for your changes and I will test and integrate it.

**Comment by akkolad** [comment]
Done, I've put my message in the issue because I've seen :
`// Starts watcher with browser-sync. Browser-sync reloads page automatically on your browser`
In the gulpfile but it doesn't work for me.

And I'm also a noob with github ;)
