### ISSUE TITLE
Sass compilation trouble

### ISSUE THREAD

**Issue by Arthurtharaud** [holger1411/understrap-child#74]
Hi Holger, 
It's the first time, I work with Sass and I want to learn how I can use it on my new projet. I have to make a new template, so I work in local with wampp and I try to use Koala to compile my css. I read the docs but I have trouble when I try to compil my css with Koala. I use the child theme. I have this error : 

```
C:\wamp\www\fondationleroch-lesmousquetaires\wp-content\themes\frm-child\sass\child-theme.scss
Error: File to import not found or unreadable: ../../src/sass/bootstrap4/variables.
       Load path: C:/wamp/www/fondationleroch-lesmousquetaires/wp-content/themes/frm-child/sass
        on line 9 of C:/wamp/www/fondationleroch-lesmousquetaires/wp-content/themes/frm-child/sass/assets/bootstrap4.scss
        from line 2 of C:\wamp\www\fondationleroch-lesmousquetaires\wp-content\themes\frm-child\sass\child-theme.scss
  Use --trace for backtrace.
```
I think that Koala doesn't  found files and the path is not good for me. How I can resolve my problem. 
Thanks.

**Comment by holger1411** [comment]
Hi!
Please make sure you run
`npm install`
in your terminal first. That command will download all dependencies and will place it inside the /src folder

**Comment by Arthurtharaud** [comment]
Hi,
Before your indication, I had not run npm install. So I've checked some tuto, because I don't have the knowledges to run npm install ( with package in my child theme). I runed `npm install` but my problem still persist. Do you know ome tuto that can help me ? 
Thanks and cheers
