### ISSUE TITLE
Multiple Slides for Hero Slider

### ISSUE THREAD

**Issue by tellstevens** [holger1411/understrap-child#77]
I'm attempting to have one hero slider that is the default settings that ships with the theme and then another at the bottom. I've gotten both sliders to work with default settings but I'd like my second to show multiple slides at once and rotate one at a time. I've looked at lots of snippets where people have achieved this but nothing seems to work for me. Do you have any recommendations for achieving this?

**Comment by holger1411** [comment]
Never tested by myself but found a solution here:
https://stackoverflow.com/questions/35152475/bootstrap-4-carousel-multiple-frames-at-once-and-slide-by-one

It shows three slides at once (by setting the item width: 33.3%; ... but if you set it to 50% you should see two only)

**Comment by holger1411** [comment]
Here is another (live and working) solution:
https://www.codeply.com/go/s3I9ivCBYH/multi-carousel-single-slide-bootstrap-4

**Comment by tellstevens** [comment]
Thanks for the direction. I was only finding bootstrap 3 examples. I'm not too savvy with jquery so just to check I'll be replacing the code below with what he has in his script correct? 
`jQuery( "#carouselExampleControls2 .carousel-item" ).first().addClass( "active" );`
