### ISSUE TITLE
Gulp CSS and SCSS Conventions

### ISSUE THREAD

**Issue by raisonon** [holger1411/understrap-child#8]
Hi, Great work.

Just working out best way to include additional bower scss and css into the child-theme.min.css

So, the gulp copy-assets can be used to copy the bower assets to the src folder. 

Then the child-theme.scss file uses @import looking in the sass/assets folder

Am I missing something or should we be pointing @import to the src folder that we just used in gulp copy-assets?

Thanks

**Comment by raisonon** [comment]
So currently i'm importing like this: @import "../src/css/uikit.min";

**Comment by holger1411** [comment]
Hi!

The /assets folder includes just the "@imports" commands for the files from /src
So its a second layer between the 3rd party assets and the understrap core. And the /assets/ files just link betwenn both of this worlds.
Its nice if you don´t need to import any Bootstrap scss files. You can just comment it out without touching the original BS core files like @import "assets/uikit"

If you import another 3rd party asset (of example UI kit) add it as bower dependency first and run "bower update"(1.) and add it to the "gulp copy-asset" task (2.) to move them from /bower_components to src/uikit and run the command.
Than create an empty uikit.scss file into /assets/sccs/ (3.)and add your import commands (4.) to it. Import from the /src folder.

Than @import your src/uikit.scss into the /sass/theme.scss file and recompile.

I know, sounds complicated, but its easier to maintain und update without breaking anything. You can work with it // commend out some parts or remove something etc. without touching the 3rd party asset or the understrap core files.

Note: And yes, you can add it with @import "../src/css/uikit.min"; right to the /sass/theme.scss file.
It will work, too without the way around using the /assets folder.
In this case you just bypass this "second layer"

**Comment by raisonon** [comment]
Interesting process. So, at the end of it we will have the file existing in 1) bower_components 2) src and 3) sass/assets

Not sure the point of the 2nd src folder.

Also you say "Than @import your src/uikit.scss into the /sass/theme.scss file and recompile." Are you talking about adding a line in the child-theme.scss with an @import?

I thought the Sass @import was just for compilation and would not copy the file from one directory to another? Am I missing something?

Many thanks for the thorough reply by the way.

**Comment by holger1411** [comment]
No, the files just exists in bower_components and /src, the /asset folder includes just the imports to compose your setup.
And no, a @import don´t move any files. It links just to the sources which are than compiled into on single css file (theme.min.css) which is used by the theme.

All scss files in the asset folder are just long lists of @imports from the /src folder. There are no real styles included, it just compose the sequenz of which file is when/where compiled into css.

The /src folder is just used to have a working copy of your 3rd party stuff. If you import anything from the /bower_component folder (which will work too) you might get problems if you run "bower update" and some essential parts are changed.
