### ISSUE TITLE
How to use Carousel

### ISSUE THREAD

**Issue by Mayccoll** [holger1411/understrap-child#9]
Hi,
I'm trying to use carousel in a child team but not success in a template file.
all other styles work fine.
I'm using Bootstrap snippet http://getbootstrap.com/javascript/#carousel
Thanks

**Comment by holger1411** [comment]
Hi! Understrap used on Bootstrap 4, not 3:
http://v4-alpha.getbootstrap.com/components/carousel/

**Comment by Mayccoll** [comment]
ooooow dam ... so sorry xD
Working fine
